// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2dijHgXHQ-CdoZ5p6dT9gCUsPGCuPHk',
    appId: '1:1028617958905:web:fb6ec12ea35c687f193928',
    messagingSenderId: '1028617958905',
    projectId: 'dojoflutter-aa6e2',
    authDomain: 'dojoflutter-aa6e2.firebaseapp.com',
    storageBucket: 'dojoflutter-aa6e2.appspot.com',
    measurementId: 'G-H79BCMRK9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWmrAnttKME1wFKMWSJJUzgYUFS539LaY',
    appId: '1:1028617958905:android:8623592730fc816a193928',
    messagingSenderId: '1028617958905',
    projectId: 'dojoflutter-aa6e2',
    storageBucket: 'dojoflutter-aa6e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI6I_GQIlnClc3Xzv5_YEUjbEoSSFUInk',
    appId: '1:1028617958905:ios:228560d6e1efd39a193928',
    messagingSenderId: '1028617958905',
    projectId: 'dojoflutter-aa6e2',
    storageBucket: 'dojoflutter-aa6e2.appspot.com',
    iosClientId: '1028617958905-sbn0tutlvpbhhsqv24kusu7smimli2hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dojoFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI6I_GQIlnClc3Xzv5_YEUjbEoSSFUInk',
    appId: '1:1028617958905:ios:228560d6e1efd39a193928',
    messagingSenderId: '1028617958905',
    projectId: 'dojoflutter-aa6e2',
    storageBucket: 'dojoflutter-aa6e2.appspot.com',
    iosClientId: '1028617958905-sbn0tutlvpbhhsqv24kusu7smimli2hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.dojoFlutterFirebase',
  );
}
